### ISSUE TITLE
[wishlist] defacer BIDS-app

### ISSUE THREAD

**Issue by yarikoptic** [BIDS-Apps/bids-apps.github.io#12]
Given a "raw" BIDS dataset, but which was not defaced yet, should deface anatomicals for all subjects/sessions, and move non-defaced under `sourcedata/`.  Could be any of the https://open-brain-consent.readthedocs.io/en/stable/anon_tools.html#faces-dental-stripping but probably ideally the one used by OpenNeuro folks themselves.  Note also that the https://github.com/mih/mridefacer/blob/master/mridefacer also has "datalad support" in that it takes care about annotating non-defaced anatomicals as having distribution restrictions.

tags to add: good for a hackathon

**Comment by PeerHerholz** [comment]
thx for referencing [BIDSonym](https://github.com/PeerHerholz/BIDSonym) @yarikoptic. It currently copies the original non-defaced images and places them under `/derivatives/bidsonym`, adding a `no_deid` identifier (e.g. `sub-01_T1w.nii.gz` --> `sub-01_T1w_no_deid.nii.gz`). However, I would be happy to implement your suggestion placing the original images under `sourcedata/` (makes way more sense). I'm super excited about the possibility of a `datalad support`, which would also remove the "necessity" of the `no_deid` identifier. I will look into this as well, following [mridefacer](https://github.com/mih/mridefacer) for "inspiration".

**Comment by PeerHerholz** [comment]
The latest [PRs](https://github.com/PeerHerholz/BIDSonym/commit/ec61d3d602980a889510041540e85d340d4d6428) to [BIDSonym](https://github.com/PeerHerholz/BIDSonym) added [mridefacer](https://github.com/mih/mridefacer) as utilizable tool and changed the main function to copy original, not de-identified images to `sourcedata/` instead of `derivatives/`. The `datalad support` will follow soon. #
